export type KeetLocaleKey = "leaveGroup" | "confirmLeave" | "leaveConfirmHint" | "cancelLeave" | "leaving" | "leaveFailed" | "title" | "description" | "workspaceId" | "workspaceHint" | "workspaceMissing" | "runtime" | "restartHint" | "save" | "saving" | "discard" | "unsaved" | "readOnly" | "saveFailed" | "required" | "unbound" | "missing-settings" | "connecting" | "ready" | "failed" | "disabled" | "memberJoinTrigger" | "memberJoinTriggerHint" | "memberJoinTriggerSaving" | "memberJoinTriggerSaved" | "memberJoinTriggerSaveFailed" | "newMessagesHint" | "invitation" | "invitationHint" | "join" | "joining" | "joinSuccess" | "pendingRequests" | "requestsHint" | "requestsLoading" | "requestsEmpty" | "refresh" | "refreshing" | "accept" | "accepting" | "acceptSuccess" | "retryAdmission" | "onboardingPartial" | "onboardingFailed"

export const keetLabels: Record<KeetLocaleKey, string> = {
  leaveGroup: "Leave group",
  confirmLeave: "Confirm leave",
  leaveConfirmHint: "The Agent will leave this group and stop receiving its messages. An invitation is needed to rejoin.",
  cancelLeave: "Cancel",
  leaving: "Leaving…",
  leaveFailed: "Could not confirm leaving. Check the bridge and refresh before retrying.",
  title: "Keet bridge",
  description: "Discover joined groups and accepted DMs in one existing DSH conversation.",
  workspaceId: "DSH workspace",
  workspaceHint: "Owns .dsh/dsh-keet/identity and supplies the latest eligible human conversation.",
  workspaceMissing: "The selected workspace is not available in this DSH deployment.",
  runtime: "Bridge readiness",
  restartHint: "A workspace change needs Save and restart. Joining or accepting needs no restart.",
  save: "Save",
  saving: "Saving…",
  discard: "Discard",
  unsaved: "Unsaved",
  readOnly: "This deployment is read-only.",
  saveFailed: "The deployment rejected these values; your draft was kept.",
  required: "Required",
  unbound: "No eligible existing conversation was found.",
  "missing-settings": "Incomplete settings",
  connecting: "Connecting…",
  ready: "Ready",
  failed: "Unavailable",
  disabled: "Stopped",
  memberJoinTrigger: "Member Join Trigger",
  memberJoinTriggerHint: "Enable member-arrival turns only for the groups you choose. Changes apply immediately; arrivals while disabled are not replayed.",
  memberJoinTriggerSaving: "Saving…",
  memberJoinTriggerSaved: "Saved",
  memberJoinTriggerSaveFailed: "Could not save",
  newMessagesHint: "New destinations start with new messages only; history is never replayed into the Agent.",
  invitation: "Invitation",
  invitationHint: "Paste a Keet room invitation to join it now.",
  join: "Join",
  joining: "Joining…",
  joinSuccess: "Joined and ready in this bridge.",
  pendingRequests: "Pending DM requests",
  requestsHint: "Open this section to load requests.",
  requestsLoading: "Loading requests…",
  requestsEmpty: "No pending DM requests.",
  refresh: "Refresh",
  refreshing: "Refreshing…",
  accept: "Accept",
  accepting: "Accepting…",
  acceptSuccess: "Accepted and ready in this bridge.",
  retryAdmission: "Retry",
  onboardingPartial: "The native action succeeded, but this destination is not ready yet.",
  onboardingFailed: "Onboarding is unavailable or failed. Check the bridge and try again.",
}

export const keetZhLabels = {
  ...keetLabels,
  title: "Keet bridge",
  description: "在一个现有 DSH 会话中发现已加入的群组和已接受的私信。",
  restartHint: "更改工作区需要保存并重启；加入或接受私信无需重启。",
  leaveGroup: "退出群聊",
  confirmLeave: "确认退出",
  leaveConfirmHint: "Agent 将退出这个群聊并停止接收消息，重新加入需要邀请。",
  cancelLeave: "取消",
  leaving: "退出中…",
  leaveFailed: "未能确认退出，请检查 bridge 并刷新后再重试。",
  memberJoinTrigger: "成员加入触发器",
  memberJoinTriggerHint: "只为你选择的群组启用成员加入触发；更改立即生效，停用期间的加入不会补发。",
  memberJoinTriggerSaving: "保存中…",
  memberJoinTriggerSaved: "已保存",
  memberJoinTriggerSaveFailed: "保存失败",
  newMessagesHint: "新目的地只接收建立接入后的新消息；历史消息不会触发 Agent。",
  invitation: "邀请",
  invitationHint: "粘贴 Keet 房间邀请即可立即加入。",
  join: "加入",
  joining: "加入中…",
  joinSuccess: "已加入并在当前 bridge 中就绪。",
  pendingRequests: "待处理私信请求",
  requestsHint: "打开此区域以加载请求。",
  requestsLoading: "正在加载请求…",
  requestsEmpty: "没有待处理的私信请求。",
  refresh: "刷新",
  refreshing: "刷新中…",
  accept: "接受",
  accepting: "接受中…",
  acceptSuccess: "已接受并在当前 bridge 中就绪。",
  retryAdmission: "重试",
  onboardingPartial: "原生操作已成功，但目的地尚未就绪。",
  onboardingFailed: "接入不可用或失败，请检查 bridge 后重试。",
} as Record<KeetLocaleKey, string>
export const keetLocale = { en: keetLabels, zh: keetZhLabels } as const
